travis: remove 3.2
The python 3.2 CI runs have been failing inside "import mock" with:

  RuntimeError: Python 3.3 or later is required

Possibly a misconfiguration on the travis side, but for now,
reduce the noise by disabling this configuration.